### PR TITLE
fix sasl transport issue; resolve #5

### LINKED ISSUE #5: Issues when query returns lots of records/rows
[impala.go.txt](https://github.com/bippio/go-impala/files/2849575/impala.go.txt)

We are running the attached client program to iterate all the DBs and then iterate the tables for each DB.

We realized there are 2 issues :

- Issue 1:  Some DBs had more than 1K tables . 
   - Interestingly the Fetch call below in rowset's Next() function would succeed (the response's data would be arbitrarily truncated which goes unnoticed) , but the RowSet's Next() call would finally fail with following error (which also goes unnoticed by the client - all that the client knows is that there are no results to iterate through)
 **GetResultsMetadata failed: get_results_metadata: wrong method name**
   - https://github.com/bippio/go-impala/blob/e316686dfb0394346755335508b8320bdf0b5964/rowset.go#L140
   - The solution seems to make sure that the fetch call requests lower number of rows , however it is not clear what the right number should be . 100 seems to work . 1000 seems to be too high.

- Issue 2 , Interestingly after the Next() call errors out, it just returns false and the client code moves on to the next query .  However all subsequent queries on that connection fail with the following error . This is extremely problematic, ideally we should be able to reset the state and start a new query even if earlier queries error out.
   -  **error in querying database X: query: wrong method name**

@timarmstrong - I would need some suggestion from you on both the issues .

Both issues seem to be stemming due to the driver's incorrect understanding of how to use the thrift interface/services. 
Any help will be appreciated to point us to a more robust way of doing this without changing the current dependency on beeswax.

@intamyuto  FYI

### PR DESCRIPTION
**Pull request by intamyuto**
* fix unexpected short read for TSaslTransport
* add fetch_size to options

### CODE REVIEW

File: rowset.go [hunk 1]
```diff
@@ -129,6 +129,7 @@ func (r *rowSet) waitForSuccess(ctx context.Context) error {
 // results are empty or any other error occurs.
 func (r *rowSet) Next(ctx context.Context) bool {
 	if err := r.waitForSuccess(ctx); err != nil {
+		log.Printf("wait for sucess failed: %v\n", err)
```
Comment (vishjosh) [inline rowset.go]: Success typo
